<a href="https://colab.research.google.com/github/code750/Deep_rearning/blob/main/3_Models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 레모네이드 판매 예측

*   github csv url : https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/lemonade.csv



In [43]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [ ]:
# 데이터 준비
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/lemonade.csv'
데이터 = pd.read_csv(파일경로)
데이터.head()

In [ ]:
# 종속변수, 독립변수
독립 = 데이터[['온도']]
종속 = 데이터[['판매량']]
print(독립.shape)
print(종속.shape)

In [46]:
# 모델을 만듭니다.
x = tf.keras.layers.Input(shape=[1])
y = tf.keras.layers.Dense(1)(x)
model = tf.keras.models.Model(x, y)
model.compile(loss='mse')

In [ ]:
# 모델을 학습시킵니다.
model.fit(독립, 종속, epochs=10)

In [ ]:
# 모델을 이용합니다.
model.predict(독립)

In [ ]:
종속

In [ ]:
model.predict([[15]])

# 보스턴 집값 예측

*   github url : https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv



In [53]:
# 라이브러리 불러오기
import tensorflow as tf
import pandas as pd

In [54]:
# 데이터 준비
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)
print(보스턴.columns)
보스턴.head()

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')


crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]

In [55]:
# 독립변수, 종속변수 분리
독립 = 보스톤[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
종속 = 보스톤[['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [56]:
# 모델 구조 만들기
x = tf.keras.layers.Input(shape=13)
y = tf.keras.layers.Dense(1)(x)
model = tf.keras.models.Model(x, y)
model.compile(loss='mse')

In [63]:
# 모델 학습시키기
model.fit(독립, 종속, epochs=10000, verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 1ms/step - loss: 23.8294
Epoch 2/10
16/16 [==============================] - 0s 997us/step - loss: 23.7544
Epoch 3/10
16/16 [==============================] - 0s 871us/step - loss: 23.6361
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 23.9462
Epoch 5/10
16/16 [==============================] - 0s 979us/step - loss: 23.3900
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 23.6091
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 24.6532
Epoch 8/10
16/16 [==============================] - 0s 1ms/step - loss: 23.5417
Epoch 9/10
16/16 [==============================] - 0s 1ms/step - loss: 23.6882
Epoch 10/10
16/16 [==============================] - 0s 1ms/step - loss: 24.0507


In [70]:
# 모델 이용하기
model.predict(독립[5:10])

array([[26.0696   ],
       [22.740864 ],
       [19.794361 ],
       [11.6685505],
       [19.115368 ]], dtype=float32)

In [71]:
종속[5:10]

medv
5  28.7
6  22.9
7  27.1
8  16.5
9  18.9

In [72]:
# 모델의 수식 확인
model.get_weights()

[array([[-0.09246199],
        [ 0.04656764],
        [-0.01822074],
        [ 2.6497767 ],
        [-3.0191631 ],
        [ 5.1788173 ],
        [-0.00834039],
        [-1.0918243 ],
        [ 0.20666437],
        [-0.01008454],
        [-0.5405671 ],
        [ 0.01391179],
        [-0.463712  ]], dtype=float32), array([9.963906], dtype=float32)]

# 아이리스 품종 분류

*   github url : https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv



In [74]:
# 라이브러리 가져오기
import tensorflow as tf
import pandas as pd

In [ ]:
# 데이터 준비
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

In [78]:
# 인핫 인코딩
인코딩 = pd.get_dummies(아이리스)
인코딩.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [79]:
print(인코딩.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [80]:
# 독립변수, 종속변수 만들기
독립 = 인코딩[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 인코딩[['품종_setosa', '품종_versicolor','품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [84]:
# 모델 구조 만들기
x = tf.keras.layers.Input(shape=[4])
y = tf.keras.layers.Dense(3, activation='softmax')(x)
model = tf.keras.models.Model(x, y)
model.compile(loss = 'categorical_crossentropy', 
              metrics = 'accuracy')

In [95]:
# 모델 학습시키기
model.fit(독립, 종속, epochs=700)

Epoch 1/700
5/5 [==============================] - 0s 3ms/step - loss: 0.0831 - accuracy: 0.9800
Epoch 2/700
5/5 [==============================] - 0s 2ms/step - loss: 0.0833 - accuracy: 0.9733
Epoch 3/700
5/5 [==============================] - 0s 2ms/step - loss: 0.0828 - accuracy: 0.9800
Epoch 4/700
5/5 [==============================] - 0s 2ms/step - loss: 0.0830 - accuracy: 0.9800
Epoch 5/700
5/5 [==============================] - 0s 4ms/step - loss: 0.0829 - accuracy: 0.9733
Epoch 6/700
5/5 [==============================] - 0s 2ms/step - loss: 0.0831 - accuracy: 0.9800
Epoch 7/700
5/5 [==============================] - 0s 3ms/step - loss: 0.0831 - accuracy: 0.9800
Epoch 8/700
5/5 [==============================] - 0s 2ms/step - loss: 0.0827 - accuracy: 0.9800
Epoch 9/700
5/5 [==============================] - 0s 4ms/step - loss: 0.0829 - accuracy: 0.9800
Epoch 10/700
5/5 [==============================] - 0s 2ms/step - loss: 0.0831 - accuracy: 0.9733
Epoch 11/700
5/5 [===========

In [100]:
# 모델 이용하기
model.predict(독립[-5:])

array([[6.6048892e-14, 1.4853619e-02, 9.8514634e-01],
       [6.5257457e-13, 4.8564009e-02, 9.5143604e-01],
       [2.2507248e-12, 7.8886807e-02, 9.2111319e-01],
       [5.3885929e-14, 1.0466192e-02, 9.8953384e-01],
       [1.5145074e-11, 1.3464516e-01, 8.6535484e-01]], dtype=float32)

In [99]:
종속[-5:]

품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1

In [101]:
# 학습한 가중치
model.get_weights()

[array([[ 2.1184483 ,  0.9859475 , -0.84948945],
        [ 6.2279515 ,  1.1405541 , -1.7455162 ],
        [-8.109291  , -1.4986109 ,  1.4576188 ],
        [-9.822709  , -2.8715699 ,  4.1419826 ]], dtype=float32),
 array([ 4.1428657,  2.7685282, -3.5848513], dtype=float32)]