<a href="https://colab.research.google.com/github/code750/Deep_rearning/blob/main/multilayer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 히든 레이어


In [1]:
# 라이브러리 불러오기
import tensorflow as tf
import pandas as pd

# 보스턴 집값 예측

*   github url : https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv



In [2]:
# 데이터 준비
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)
print(보스턴.columns)
보스턴.head()

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')


crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]

In [4]:
# 독립변수, 종속변수 분리
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [5]:
# 모델 구조 만들기
x = tf.keras.layers.Input(shape=13)
h = tf.keras.layers.Dense(10, activation='swish')(x)
y = tf.keras.layers.Dense(1)(h)
model = tf.keras.models.Model(x, y)
model.compile(loss='mse')

In [13]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense (Dense)                (None, 10)                140       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [11]:
# 모델 학습시키기
model.fit(독립, 종속, epochs=500)

Epoch 1/500
16/16 [==============================] - 0s 1ms/step - loss: 18.1284
Epoch 2/500
16/16 [==============================] - 0s 2ms/step - loss: 18.5149
Epoch 3/500
16/16 [==============================] - 0s 2ms/step - loss: 18.6143
Epoch 4/500
16/16 [==============================] - 0s 1ms/step - loss: 17.8397
Epoch 5/500
16/16 [==============================] - 0s 1ms/step - loss: 18.4265
Epoch 6/500
16/16 [==============================] - 0s 1ms/step - loss: 17.2139
Epoch 7/500
16/16 [==============================] - 0s 1ms/step - loss: 17.6748
Epoch 8/500
16/16 [==============================] - 0s 1ms/step - loss: 18.0877
Epoch 9/500
16/16 [==============================] - 0s 1ms/step - loss: 17.6479
Epoch 10/500
16/16 [==============================] - 0s 1ms/step - loss: 18.1714
Epoch 11/500
16/16 [==============================] - 0s 1ms/step - loss: 19.0164
Epoch 12/500
16/16 [==============================] - 0s 1ms/step - loss: 17.5641
Epoch 13/500
16/16 [=====

In [16]:
# 모델 이용하기
print(model.predict(독립[0:5]))
print(종속[:5])

[[28.08895 ]
 [23.094501]
 [29.129612]
 [28.74078 ]
 [28.665024]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


In [ ]:
종속[5:10]

medv
5  28.7
6  22.9
7  27.1
8  16.5
9  18.9

In [ ]:
# 모델의 수식 확인
model.get_weights()

[array([[-0.09246199],
        [ 0.04656764],
        [-0.01822074],
        [ 2.6497767 ],
        [-3.0191631 ],
        [ 5.1788173 ],
        [-0.00834039],
        [-1.0918243 ],
        [ 0.20666437],
        [-0.01008454],
        [-0.5405671 ],
        [ 0.01391179],
        [-0.463712  ]], dtype=float32), array([9.963906], dtype=float32)]

# 아이리스 품종 분류

*   github url : https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv



In [25]:
# 라이브러리 가져오기
import tensorflow as tf
import pandas as pd

In [26]:
# 데이터 준비
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [27]:
# 인핫 인코딩
인코딩 = pd.get_dummies(아이리스)
인코딩.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [28]:
print(인코딩.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [29]:
# 독립변수, 종속변수 만들기
독립 = 인코딩[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 인코딩[['품종_setosa', '품종_versicolor','품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [30]:
# 모델 구조 만들기
x = tf.keras.layers.Input(shape=[4])
h = tf.keras.layers.Dense(8, activation='swish')(x)
h = tf.keras.layers.Dense(8, activation='swish')(h)
h = tf.keras.layers.Dense(8, activation='swish')(h)
y = tf.keras.layers.Dense(3, activation='softmax')(h)
model = tf.keras.models.Model(x, y)
model.compile(loss = 'categorical_crossentropy', 
              metrics = 'accuracy')

In [32]:
# 모델 학습시키기
model.fit(독립, 종속, epochs=100)

Epoch 1/100
5/5 [==============================] - 0s 5ms/step - loss: 0.9333 - accuracy: 0.4667
Epoch 2/100
5/5 [==============================] - 0s 4ms/step - loss: 0.9107 - accuracy: 0.5400
Epoch 3/100
5/5 [==============================] - 0s 5ms/step - loss: 0.8876 - accuracy: 0.5467
Epoch 4/100
5/5 [==============================] - 0s 3ms/step - loss: 0.8663 - accuracy: 0.5533
Epoch 5/100
5/5 [==============================] - 0s 4ms/step - loss: 0.8454 - accuracy: 0.5733
Epoch 6/100
5/5 [==============================] - 0s 4ms/step - loss: 0.8252 - accuracy: 0.5533
Epoch 7/100
5/5 [==============================] - 0s 4ms/step - loss: 0.8060 - accuracy: 0.6200
Epoch 8/100
5/5 [==============================] - 0s 4ms/step - loss: 0.7882 - accuracy: 0.6267
Epoch 9/100
5/5 [==============================] - 0s 3ms/step - loss: 0.7701 - accuracy: 0.6400
Epoch 10/100
5/5 [==============================] - 0s 5ms/step - loss: 0.7536 - accuracy: 0.6467
Epoch 11/100
5/5 [===========

In [34]:
# 모델 이용하기
print(model.predict(독립[0:5]))
print(종속[0:5])

[[9.9939561e-01 6.0433568e-04 6.6045639e-25]
 [9.9675578e-01 3.2442454e-03 6.9227656e-22]
 [9.9859267e-01 1.4073639e-03 8.7975377e-23]
 [9.9599719e-01 4.0028607e-03 9.0009456e-21]
 [9.9952722e-01 4.7276518e-04 4.7287646e-25]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [35]:
종속[0:5]

품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0

In [ ]:
# 학습한 가중치
model.get_weights()

[array([[ 2.1184483 ,  0.9859475 , -0.84948945],
        [ 6.2279515 ,  1.1405541 , -1.7455162 ],
        [-8.109291  , -1.4986109 ,  1.4576188 ],
        [-9.822709  , -2.8715699 ,  4.1419826 ]], dtype=float32),
 array([ 4.1428657,  2.7685282, -3.5848513], dtype=float32)]